### ISSUE TITLE
Angular template not picking up the changes from the subscription

### ISSUE THREAD

**Issue by AnthonyCC** [apollographql/apollo-angular#295]
Hi,

I am using `apollo-angular` + `subscriptions-transport-ws` in my project. I have the client setup to listen to the subscription for user's password updated or new user is created event. This is how it is setup
```
//Apollo Subscription
this.apollo.subscribe({
  query: this.passwordUpdatedSubscription
}).subscribe(({passwordUpdated}:any) => {
  return this.userDataQuery.updateQuery((previousResult) => {
	let userIndex = previousResult.getUsers.findIndex(user => user.name === passwordUpdated.name);
	let updatedUsers;
	if (userIndex === -1) {
	  updatedUsers = [].concat(previousResult.getUsers).concat([passwordUpdated]);

	} else {
	  updatedUsers = [].concat(previousResult.getUsers.slice(0, userIndex)).concat([passwordUpdated]);
	  if (userIndex !== previousResult.getUsers.length - 1) {
		updatedUsers = updatedUsers.concat(previousResult.getUsers.slice(userIndex + 1));
	  }

	}
	return Object.assign({}, previousResult, {
	  getUsers: updatedUsers,
	});
  });

});
```

It seems to be working fine and does its job to notify the `userDataQuery` about the update. In the `userDataQuery`, it handles the updates this way
```
this.userDataQuery = this.apollo.watchQuery({
  query: this.getUsersQuery
}).subscribe(({data}:any) => {
  this.userData = data.getUsers;
  // I have to call detectChanges to tell Angular to render the template.
  // is there anyway to avoid doing this?
  //this.ref.detectChanges();

});
```

The userData did get updated successfully, However, the changes is not reflected on the template. I will have to call `this.ref.detectChanges();` to update the template.

The template is very simple
```
<span ng-if="userData">{{userData && userData[0] && userData[0].password}}</span>
```

Is there anything I missed in my code. I thought the template would pick up the change automatically ?

**Comment by Urigo** [comment]
this is interesting and I've had that happen to me as well...
I'm investigating..

**Comment by kamilkisiela** [comment]
Should be fixed by #297

**Comment by AnthonyCC** [comment]
I pulled the latest but unfortunately it didn't completely fix the issue. It did however update the UI sometimes. I noticed that the UI will reflect the changes when you made the changes 2x times, ie, the UI will be updated when you made changes on the 2nd, 4th, 6th ... times

**Comment by Urigo** [comment]
I've published the package a bit later, @AnthonyCC can you test again with `0.13.0` just to make sure?

**Comment by hansol-shin** [comment]
I have same problem with 0.13.0.

**Comment by AnthonyCC** [comment]
Sure, I tested w/ `0.13.0` and had the same result.

**Comment by kamilkisiela** [comment]
@AnthonyCC If the UI changes only after another update happens it means that the first update happens but it's not visible to Angular's change detection. This is why I created `ZoneScheduler`, to put it inside the Zone queue. Could you somehow create a minimal reproduction? It will be veeeeeryyy helpful. All my examples work so I have no clue how it's still a thing.

**Comment by jeremyputeaux** [comment]
@kamilkisiela I'm experimenting the same thing with `0.13.0`. I made a post on [stackoverflow](http://stackoverflow.com/questions/43103461/whats-wrong-with-this-subscription-i-get-updates-but-the-view-is-not-refreshed). I hope it helps.

**Comment by AnthonyCC** [comment]
@kamilkisiela , this is the demo app I used atm. https://github.com/AnthonyCC/graphQL-Demo. Currently it is setup to use Mongo db to get/save data. If you have problem setting it up, I can make it simpler sometimes this week. just let me know. Thanks for checking the issue. :)

**Comment by kamilkisiela** [comment]
@AnthonyCC I will try to check your app but for now I created an example app with graph.cool as a backend.

I used:
```json
{
  "apollo-angular": "0.13.0",
  "apollo-client": "1.0.3",
  "graphql-tag": "2.0.0",
  "subscriptions-transport-ws": "0.5.5"
}
```

Here's my working app:
https://github.com/kamilkisiela/angular-graphql-subcriptions

**Comment by cyberbeast** [comment]
I am using the apollo-server package with express, and my view is not getting updated after the subscription changes are detected. Is this a problem with the apollo-angular package? Also there isn't any documentation about subscription in the apollo-angular docs? Is this intentional?

**Comment by kamilkisiela** [comment]
I tried to reproduce it within a test - here it is #312

**Comment by altschuler** [comment]
Having the same issues. In this case I'm not listening directly to the updates, but watching fragments which are updated by the subscription results. I'm pretty sure it worked all fine at some point and I suspect it might have changed with some angular update. FWIW I tried to do "fix" it with `ApplicationRef.tick` and a setTimeout with 0 delay, which "fixed" it, except not in Firefox... Will report back if I get anywhere closer to the cause.

**Comment by altschuler** [comment]
FWIW I worked around this by running a an `ApplicationRef.tick`, in a `setTimeout` with 100ms delay, manually in the angular zone, after subscriptions come back from the server. 

Eg
```
this.apollo
    .subscribe(...)
    // Manually trigger CD after the update
    .do(() => this.zone.run(() => setTimeout(() => this.appRef.tick(), 100)));
```

Terrible, I know, but seems to solve the issue for now. I have a hunch that it has something to do with zone.js and/or how this library wraps the observable to run in the zone. Zone.js recently (about a month ago) added some [patch](https://github.com/angular/zone.js/blob/master/CHANGELOG.md#0814-2017-07-20) to make rxjs run in the correct zone, not sure if that has anything to do without, I tried older versions to no avail.

**Comment by kamilkisiela** [comment]
Works in v1.0

**Comment by BhaskaranR** [comment]
not working for me i checked it with v1.0. i wanted to show number of updates per millisecond with updates property. it wouldn't work. i have OnPush set on the component

```
   this.apollo.subscribe({
            query: getExecutionsSubscription,
            variables: { filterId: '' },
        }).subscribe((subscriptionData: any) => {
            const tradeupdates: TradeUpdates[] = subscriptionData.getExecutions;
            this.updates = tradeupdates.length;
            }
        });
```
