### ISSUE TITLE
response type missing after update cache in Mutate

### ISSUE THREAD

**Issue by mattiLeBlanc** [apollographql/apollo-angular#880]
My  response variable `data` in the `update function` is currently untyped and defaulted to `{}` instead of `updateUser`.

```
    this.updateUserGQL
      .mutate( this.userForm.value, {
        context: {
          headers: {
            "Authorization": `Bearer ${ this.bearer }`
          }
        },
        optimisticResponse: {
          updateUser: {
            __typename: 'User',
            id: -1,
            firstName: this.userForm.value.firstName,
            lastName: this.userForm.value.lastName,
          }
        },
        update: ( proxy, { data: { updateUser } } ) => {
          const data = proxy.readQuery( { query: this.allUsersGQL.document } );

          data.allUsers.unshift(updateUser);  // <--- allUsers is unknown since updateUser is of type {}

          proxy.writeQuery( { query: this.allUsersGQL.document, data } );
        }
      } )
      .subscribe( data => console.log( 'first', data ) );

--------------- query def ------------------

   export interface User {
      firstName: string;
      lastName: string;
      id: string;
    
    }
    
    export interface UserResponse {
      allUsers: User[];
    }
    
    
    
    export class UpdateUserGQL extends Mutation<UserResponse> {
      document = gql`
        mutation updateUser( $id: ID!, $firstName: String!, $lastName: String! ) {
          updateUser( id: $id, firstName: $firstName, lastName: $lastName ) {
            id
            firstName
            lastName
          }
        }
      `;
    } 
```

Adding the generic to the Mutation extension of `UpdateUserGQL` didn't do the trick.
The only thing I can do is change the update function like this:
```update: <any>( proxy, { data: { updateUser } } ) => {```
which makes it an `any` instead of `{}`.

Is this an omission or did I do something wrong?

**Comment by kamilkisiela** [comment]
#885 should fix it. There was generic types till v2.3.6 of Apollo Client so that's why there's an empty object everywhere.

**Comment by kamilkisiela** [comment]
You can check out `1.5.0-alpha.69e5be2`. Could you tell me if it works for you?

**Comment by mattiLeBlanc** [comment]
No, it doesn't resolve the generic type issue on `update ( proxy`. `data.allUsers` is typed as `{}`

**Comment by kamilkisiela** [comment]
Yes, but now it's because of https://github.com/apollographql/apollo-link/issues/616

**Comment by kamilkisiela** [comment]
Closing since this issue is related to `apollo-client` and `apollo-link` and everything that I could do and already did here is released as `1.5.0-rc.0` and will be released after Angular 7 is out.
